site_name: Mkdocs blog
site_url: https://shenweiyan.github.io/mkdocs-blog
site_description: 'Testing for Mkdocs blog'
docs_dir: "docs"
site_dir: "site"
extra_css: 
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
theme:
  name: material
  font:
    text: "Microsoft Yahei"
    code: "Consolas,Courier,courier new,stkaiti,kaiti,simkai,monospace"
  language: zh
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.sections
    - navigation.path          # Sponsors only
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.footer
  palette:
    - scheme: default
      primary: grey
      accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: indigo
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode

# Repository
repo_name: mkdocs-blog
repo_url: https://github.com/shenweiyan/mkdocs-blog/
edit_uri: edit/main/docs/
site_author: Steven Shum


nav:
    - Blog: 
        - blog/index.md
    
plugins:
  - search:
      separator: '[\s\u200b\-]'
  - blog:
      blog_dir: blog
      post_dir: "{blog}/posts"
      archive: true
      categories: true
      pagination: true
      pagination_per_page: 5

hooks:
  - hooks.py
