name: mkdocs-deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Git configure
        run: |
          git config --global user.name "shenweiyan"
          git config --global user.email "weiyanshum@gmail.com"

      - name: Git Pull
        run: git pull

      - name: Install Python3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Commit files
        run: |
          echo `date +"%Y-%m-%d %H:%M:%S"` begin ... > time.txt
          git add .
          git commit -a -m "Add Changes" 

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch: main

      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force
